# https://github.com/charliermarsh/ruff
# https://beta.ruff.rs/docs/
# https://beta.ruff.rs/docs/rules/#rules

[tool.ruff]
extend-select = [
    "C4",
    "SIM",
    "TCH",
    "I"
]
show-fixes = true
line-length = 119

# Assume Python 3.10.
target-version = "py310"